### ISSUE TITLE
Requires an update to work with NpgSQL 5x

### ISSUE THREAD

**Issue by wsalik** [b00ted/serilog-sinks-postgresql#34]
Due to a breaking change in NpgSQL 5x, sink fails to save data in table.
Breaking change is: NpgsqlBinaryImporter.Complete() has been changed to return a ulong reporting the number of imported rows (#2112).
The exception thrown is:
Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: System.MissingMethodException: Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

**Comment by DouglasKreider** [comment]
Do you have an update on a fix for this?

**Comment by b00ted** [comment]
fixed in 2.3.0

**Comment by jmsvl** [comment]
This error is still happening when using this sink in .Net Framework 4.8

**Comment by augustoproiete** [comment]
Hey @b00ted I tried to send you a couple of emails a few weeks ago to the address associated with your commits in this repo, but didn't hear back yet. What's the best way to contact you privately?

**Comment by SeppPenner** [comment]
Repo is dead, try https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative.
